// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: psdbconnect/v1alpha1/connect.proto

package psdbconnectv1alpha1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha1 "github.com/planetscale/psdb/types/psdbconnect/v1alpha1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectName is the fully-qualified name of the Connect service.
	ConnectName = "psdbconnect.v1alpha1.Connect"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectSyncProcedure is the fully-qualified name of the Connect's Sync RPC.
	ConnectSyncProcedure = "/psdbconnect.v1alpha1.Connect/Sync"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	connectServiceDescriptor    = v1alpha1.File_psdbconnect_v1alpha1_connect_proto.Services().ByName("Connect")
	connectSyncMethodDescriptor = connectServiceDescriptor.Methods().ByName("Sync")
)

// ConnectClient is a client for the psdbconnect.v1alpha1.Connect service.
type ConnectClient interface {
	// Sync will continuously stream data from a PlanetScale database given a table, keyspace and shard.
	// Sync also allows you to incrementally sync data from a table given a TableCursor that is returned as part of the SyncResponse.
	// If the last known position is empty, Sync will download all the rows for a given table in a shard
	// and then wait to stream any changes to the table (inserts/updates/deletes)
	// If the last known position is not empty, Sync will pickup where the last Sync session left off and stream
	// any changes to the table since the last Sync session.
	Sync(context.Context, *connect.Request[v1alpha1.SyncRequest]) (*connect.ServerStreamForClient[v1alpha1.SyncResponse], error)
}

// NewConnectClient constructs a client for the psdbconnect.v1alpha1.Connect service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &connectClient{
		sync: connect.NewClient[v1alpha1.SyncRequest, v1alpha1.SyncResponse](
			httpClient,
			baseURL+ConnectSyncProcedure,
			connect.WithSchema(connectSyncMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectClient implements ConnectClient.
type connectClient struct {
	sync *connect.Client[v1alpha1.SyncRequest, v1alpha1.SyncResponse]
}

// Sync calls psdbconnect.v1alpha1.Connect.Sync.
func (c *connectClient) Sync(ctx context.Context, req *connect.Request[v1alpha1.SyncRequest]) (*connect.ServerStreamForClient[v1alpha1.SyncResponse], error) {
	return c.sync.CallServerStream(ctx, req)
}

// ConnectHandler is an implementation of the psdbconnect.v1alpha1.Connect service.
type ConnectHandler interface {
	// Sync will continuously stream data from a PlanetScale database given a table, keyspace and shard.
	// Sync also allows you to incrementally sync data from a table given a TableCursor that is returned as part of the SyncResponse.
	// If the last known position is empty, Sync will download all the rows for a given table in a shard
	// and then wait to stream any changes to the table (inserts/updates/deletes)
	// If the last known position is not empty, Sync will pickup where the last Sync session left off and stream
	// any changes to the table since the last Sync session.
	Sync(context.Context, *connect.Request[v1alpha1.SyncRequest], *connect.ServerStream[v1alpha1.SyncResponse]) error
}

// NewConnectHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectHandler(svc ConnectHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectSyncHandler := connect.NewServerStreamHandler(
		ConnectSyncProcedure,
		svc.Sync,
		connect.WithSchema(connectSyncMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/psdbconnect.v1alpha1.Connect/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectSyncProcedure:
			connectSyncHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectHandler struct{}

func (UnimplementedConnectHandler) Sync(context.Context, *connect.Request[v1alpha1.SyncRequest], *connect.ServerStream[v1alpha1.SyncResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("psdbconnect.v1alpha1.Connect.Sync is not implemented"))
}
